package com.example.playground.repository

import com.example.playground.data.db.entity.MusicEntity
import com.example.playground.ui.manage.MusicModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext

class MainRepositoryMock {

    suspend fun getMusicas(): MutableList<MusicEntity> {
        return withContext(Dispatchers.Default) {
            delay(3000)
            SampleData.musicsEntity
        }
    }
}

object SampleData {
    val musicsEntity = mutableListOf(
        MusicEntity(1, "Achilles Last Stand", "Led Zeppelin"),
        MusicEntity(2, "All My Love", "Led Zeppelin"),
        MusicEntity(3, "Babe I'm Gonna Leave You", "Led Zeppelin"),
        MusicEntity(4, "Baby Come On Home", "Led Zeppelin"),
        MusicEntity(5, "Bathroom Sound", "Led Zeppelin"),
        MusicEntity(6, "Black Country Woman", "Led Zeppelin"),
        MusicEntity(7, "Black Dog", "Led Zeppelin"),
        MusicEntity(8, "Black Mountain Side", "Led Zeppelin"),
        MusicEntity(9, "Bonzo's Montreux", "Led Zeppelin"),
        MusicEntity(10, "Boogie with Stu", "Led Zeppelin"),
        MusicEntity(11, "Bring It On Home", "Led Zeppelin"),
        MusicEntity(12, "Bron-Y-Aur Stomp", "Led Zeppelin"),
        MusicEntity(13, "Bron-Yr-Aur", "Led Zeppelin"),
        MusicEntity(14, "C'mon Everybody", "Led Zeppelin"),
        MusicEntity(15, "Candy Store Rock", "Led Zeppelin"),
        MusicEntity(16, "Carouselambra", "Led Zeppelin"),
        MusicEntity(17, "Celebration Day", "Led Zeppelin"),
        MusicEntity(18, "Communication Breakdown", "Led Zeppelin"),
        MusicEntity(19, "Custard Pie", "Led Zeppelin"),
        MusicEntity(20, "D'Yer Mak'er", "Led Zeppelin"),
        MusicEntity(21, "Dancing Days", "Led Zeppelin"),
        MusicEntity(22, "Darlene", "Led Zeppelin"),
        MusicEntity(23, "Dazed and Confused", "Led Zeppelin"),
        MusicEntity(24, "Down by the Seaside", "Led Zeppelin"),
        MusicEntity(25, "Fool in the Rain", "Led Zeppelin"),
        MusicEntity(26, "For Your Life", "Led Zeppelin"),
        MusicEntity(27, "Four Sticks", "Led Zeppelin"),
        MusicEntity(28, "Friends", "Led Zeppelin"),
        MusicEntity(29, "Gallows Pole", "Led Zeppelin"),
        MusicEntity(30, "Going to California", "Led Zeppelin"),
        MusicEntity(31, "Good Times Bad Times", "Led Zeppelin"),
        MusicEntity(32, "Hats Off to (Roy) Harper", "Led Zeppelin"),
        MusicEntity(33, "Heartbreaker", "Led Zeppelin"),
        MusicEntity(34, "Hey Hey What Can I Do", "Led Zeppelin"),
        MusicEntity(35, "Hot Dog", "Led Zeppelin"),
        MusicEntity(36, "Hots On for Nowhere", "Led Zeppelin"),
        MusicEntity(37, "Houses of the Holy", "Led Zeppelin"),
        MusicEntity(38, "How Many More Times", "Led Zeppelin"),
        MusicEntity(39, "I Can't Quit You Baby", "Led Zeppelin"),
        MusicEntity(40, "I'm Gonna Crawl", "Led Zeppelin"),
        MusicEntity(41, "Immigrant Song", "Led Zeppelin"),
        MusicEntity(42, "In My Time of Dying", "Led Zeppelin"),
        MusicEntity(43, "In The Evening", "Led Zeppelin"),
        MusicEntity(44, "In The Light", "Led Zeppelin"),
        MusicEntity(45, "Jennings Farm Blues", "Led Zeppelin"),
        MusicEntity(46, "Kashmir", "Led Zeppelin"),
        MusicEntity(47, "Key to the Highway/Trouble inMind", "Led Zeppelin"),
        MusicEntity(48, "LA Drone", "Led Zeppelin"),
        MusicEntity(49, "La La", "Led Zeppelin"),
        MusicEntity(50, "Living Loving Main (She'sJust a Woman)", "Led Zeppelin"),
        MusicEntity(51, "Misty Mountain Hop", "Led Zeppelin"),
        MusicEntity(52, "Moby Dick", "Led Zeppelin"),
        MusicEntity(53, "Night Flight", "Led Zeppelin"),
        MusicEntity(54, "No Quarter", "Led Zeppelin"),
        MusicEntity(55, "Nobody's Fault but Mine", "Led Zeppelin"),
        MusicEntity(56, "Out on the Tiles", "Led Zeppelin"),
        MusicEntity(57, "Over the Hills and Far Away", "Led Zeppelin"),
        MusicEntity(58, "Ozone Baby", "Led Zeppelin"),
        MusicEntity(59, "Poor Tom", "Led Zeppelin"),
        MusicEntity(60, "Ramble On", "Led Zeppelin"),
        MusicEntity(61, "Rock and Roll", "Led Zeppelin"),
        MusicEntity(62, "Royal Orleans", "Led Zeppelin"),
        MusicEntity(63, "Sick Again", "Led Zeppelin"),
        MusicEntity(64, "Since I've Been Loving You", "Led Zeppelin"),
        MusicEntity(65, "Somethin' Else", "Led Zeppelin"),
        MusicEntity(66, "South Bound Suarez", "Led Zeppelin"),
        MusicEntity(67, "Stairway to Heaven", "Led Zeppelin"),
        MusicEntity(68, "Tangerine", "Led Zeppelin"),
        MusicEntity(69, "Tea for One", "Led Zeppelin"),
        MusicEntity(70, "Ten Years Gone", "Led Zeppelin"),
        MusicEntity(71, "Thank You", "Led Zeppelin"),
        MusicEntity(72, "That's the Way", "Led Zeppelin"),
        MusicEntity(73, "The Battle of Evermore", "Led Zeppelin"),
        MusicEntity(74, "The Crunge", "Led Zeppelin"),
        MusicEntity(75, "The Girl I Love She Got LongBlack Wavy Hair", "Led Zeppelin"),
        MusicEntity(76, "The Lemon Song", "Led Zeppelin"),
        MusicEntity(77, "The Ocean", "Led Zeppelin"),
        MusicEntity(78, "The Rain Song", "Led Zeppelin"),
        MusicEntity(79, "The Rover", "Led Zeppelin"),
        MusicEntity(80, "The Song Remains the Same", "Led Zeppelin"),
        MusicEntity(81, "The Wanton Song", "Led Zeppelin"),
        MusicEntity(82, "Trampled Under Foot", "Led Zeppelin"),
        MusicEntity(83, "Travelling Riverside Blues", "Led Zeppelin"),
        MusicEntity(84, "Walter's Walk", "Led Zeppelin"),
        MusicEntity(85, "We're Gonna Groove", "Led Zeppelin"),
        MusicEntity(86, "Wearing and Tearing", "Led Zeppelin"),
        MusicEntity(87, "What Is and What ShouldNever Be", "Led Zeppelin"),
        MusicEntity(88, "When the Levee Breaks", "Led Zeppelin"),
        MusicEntity(89, "White Summer/Black MountainSide", "Led Zeppelin"),
        MusicEntity(90, "Whole Lotta Love", "Led Zeppelin"),
        MusicEntity(91, "You Shook Me", "Led Zeppelin"),
        MusicEntity(92, "Your Time Is Gonna Come", "Led Zeppelin")
    )

    val musicsModel = listOf(
        MusicModel(1, "Achilles Last Stand", "Led Zeppelin"),
        MusicModel(2, "All My Love", "Led Zeppelin"),
        MusicModel(3, "Babe I'm Gonna Leave You", "Led Zeppelin"),
        MusicModel(4, "Baby Come On Home", "Led Zeppelin"),
        MusicModel(5, "Bathroom Sound", "Led Zeppelin"),
        MusicModel(6, "Black Country Woman", "Led Zeppelin"),
        MusicModel(7, "Black Dog", "Led Zeppelin"),
        MusicModel(8, "Black Mountain Side", "Led Zeppelin"),
        MusicModel(9, "Bonzo's Montreux", "Led Zeppelin"),
        MusicModel(10, "Boogie with Stu", "Led Zeppelin"),
        MusicModel(11, "Bring It On Home", "Led Zeppelin"),
        MusicModel(12, "Bron-Y-Aur Stomp", "Led Zeppelin"),
        MusicModel(13, "Bron-Yr-Aur", "Led Zeppelin"),
        MusicModel(14, "C'mon Everybody", "Led Zeppelin"),
        MusicModel(15, "Candy Store Rock", "Led Zeppelin"),
        MusicModel(16, "Carouselambra", "Led Zeppelin"),
        MusicModel(17, "Celebration Day", "Led Zeppelin"),
        MusicModel(18, "Communication Breakdown", "Led Zeppelin"),
        MusicModel(19, "Custard Pie", "Led Zeppelin"),
        MusicModel(20, "D'Yer Mak'er", "Led Zeppelin"),
        MusicModel(21, "Dancing Days", "Led Zeppelin"),
        MusicModel(22, "Darlene", "Led Zeppelin"),
        MusicModel(23, "Dazed and Confused", "Led Zeppelin"),
        MusicModel(24, "Down by the Seaside", "Led Zeppelin"),
        MusicModel(25, "Fool in the Rain", "Led Zeppelin"),
        MusicModel(26, "For Your Life", "Led Zeppelin"),
        MusicModel(27, "Four Sticks", "Led Zeppelin"),
        MusicModel(28, "Friends", "Led Zeppelin"),
        MusicModel(29, "Gallows Pole", "Led Zeppelin"),
        MusicModel(30, "Going to California", "Led Zeppelin"),
        MusicModel(31, "Good Times Bad Times", "Led Zeppelin"),
        MusicModel(32, "Hats Off to (Roy) Harper", "Led Zeppelin"),
        MusicModel(33, "Heartbreaker", "Led Zeppelin"),
        MusicModel(34, "Hey Hey What Can I Do", "Led Zeppelin"),
        MusicModel(35, "Hot Dog", "Led Zeppelin"),
        MusicModel(36, "Hots On for Nowhere", "Led Zeppelin"),
        MusicModel(37, "Houses of the Holy", "Led Zeppelin"),
        MusicModel(38, "How Many More Times", "Led Zeppelin"),
        MusicModel(39, "I Can't Quit You Baby", "Led Zeppelin"),
        MusicModel(40, "I'm Gonna Crawl", "Led Zeppelin"),
        MusicModel(41, "Immigrant Song", "Led Zeppelin"),
        MusicModel(42, "In My Time of Dying", "Led Zeppelin"),
        MusicModel(43, "In The Evening", "Led Zeppelin"),
        MusicModel(44, "In The Light", "Led Zeppelin"),
        MusicModel(45, "Jennings Farm Blues", "Led Zeppelin"),
        MusicModel(46, "Kashmir", "Led Zeppelin"),
        MusicModel(47, "Key to the Highway/Trouble inMind", "Led Zeppelin"),
        MusicModel(48, "LA Drone", "Led Zeppelin"),
        MusicModel(49, "La La", "Led Zeppelin"),
        MusicModel(50, "Living Loving Main (She'sJust a Woman)", "Led Zeppelin"),
        MusicModel(51, "Misty Mountain Hop", "Led Zeppelin"),
        MusicModel(52, "Moby Dick", "Led Zeppelin"),
        MusicModel(53, "Night Flight", "Led Zeppelin"),
        MusicModel(54, "No Quarter", "Led Zeppelin"),
        MusicModel(55, "Nobody's Fault but Mine", "Led Zeppelin"),
        MusicModel(56, "Out on the Tiles", "Led Zeppelin"),
        MusicModel(57, "Over the Hills and Far Away", "Led Zeppelin"),
        MusicModel(58, "Ozone Baby", "Led Zeppelin"),
        MusicModel(59, "Poor Tom", "Led Zeppelin"),
        MusicModel(60, "Ramble On", "Led Zeppelin"),
        MusicModel(61, "Rock and Roll", "Led Zeppelin"),
        MusicModel(62, "Royal Orleans", "Led Zeppelin"),
        MusicModel(63, "Sick Again", "Led Zeppelin"),
        MusicModel(64, "Since I've Been Loving You", "Led Zeppelin"),
        MusicModel(65, "Somethin' Else", "Led Zeppelin"),
        MusicModel(66, "South Bound Suarez", "Led Zeppelin"),
        MusicModel(67, "Stairway to Heaven", "Led Zeppelin"),
        MusicModel(68, "Tangerine", "Led Zeppelin"),
        MusicModel(69, "Tea for One", "Led Zeppelin"),
        MusicModel(70, "Ten Years Gone", "Led Zeppelin"),
        MusicModel(71, "Thank You", "Led Zeppelin"),
        MusicModel(72, "That's the Way", "Led Zeppelin"),
        MusicModel(73, "The Battle of Evermore", "Led Zeppelin"),
        MusicModel(74, "The Crunge", "Led Zeppelin"),
        MusicModel(75, "The Girl I Love She Got LongBlack Wavy Hair", "Led Zeppelin"),
        MusicModel(76, "The Lemon Song", "Led Zeppelin"),
        MusicModel(77, "The Ocean", "Led Zeppelin"),
        MusicModel(78, "The Rain Song", "Led Zeppelin"),
        MusicModel(79, "The Rover", "Led Zeppelin"),
        MusicModel(80, "The Song Remains the Same", "Led Zeppelin"),
        MusicModel(81, "The Wanton Song", "Led Zeppelin"),
        MusicModel(82, "Trampled Under Foot", "Led Zeppelin"),
        MusicModel(83, "Travelling Riverside Blues", "Led Zeppelin"),
        MusicModel(84, "Walter's Walk", "Led Zeppelin"),
        MusicModel(85, "We're Gonna Groove", "Led Zeppelin"),
        MusicModel(86, "Wearing and Tearing", "Led Zeppelin"),
        MusicModel(87, "What Is and What ShouldNever Be", "Led Zeppelin"),
        MusicModel(88, "When the Levee Breaks", "Led Zeppelin"),
        MusicModel(89, "White Summer/Black MountainSide", "Led Zeppelin"),
        MusicModel(90, "Whole Lotta Love", "Led Zeppelin"),
        MusicModel(91, "You Shook Me", "Led Zeppelin"),
        MusicModel(92, "Your Time Is Gonna Come", "Led Zeppelin")
    )
}