package com.example.playground.ui.main

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext

class MainRepository {

    suspend fun getMusicas() : MutableList<Musica>{
        return withContext(Dispatchers.Default){
            delay(3000)
            mutableListOf(
                Musica(1,"Achilles Last Stand"),
                Musica(2,"All My Love"),
                Musica(3,"Babe I'm Gonna Leave You"),
                Musica(4,"Baby Come On Home"),
                Musica(5,"Bathroom Sound"),
                Musica(6,"Black Country Woman"),
                Musica(7,"Black Dog"),
                Musica(8,"Black Mountain Side"),
                Musica(9,"Bonzo's Montreux"),
                Musica(10,"Boogie with Stu"),
                Musica(11,"Bring It On Home"),
                Musica(12,"Bron-Y-Aur Stomp"),
                Musica(13,"Bron-Yr-Aur"),
                Musica(14,"C'mon Everybody"),
                Musica(15,"Candy Store Rock"),
                Musica(16,"Carouselambra"),
                Musica(17,"Celebration Day"),
                Musica(18,"Communication Breakdown"),
                Musica(19,"Custard Pie"),
                Musica(20,"D'Yer Mak'er"),
                Musica(21,"Dancing Days"),
                Musica(22,"Darlene")/*,
                Musica(23,"Dazed and Confused"),
                Musica(24,"Down by the Seaside"),
                Musica(25,"Fool in the Rain"),
                Musica(26,"For Your Life"),
                Musica(27,"Four Sticks"),
                Musica(28,"Friends"),
                Musica(29,"Gallows Pole"),
                Musica(30,"Going to California"),
                Musica(31,"Good Times Bad Times"),
                Musica(32,"Hats Off to (Roy) Harper"),
                Musica(33,"Heartbreaker"),
                Musica(34,"Hey Hey What Can I Do"),
                Musica(35,"Hot Dog"),
                Musica(36,"Hots On for Nowhere"),
                Musica(37,"Houses of the Holy"),
                Musica(38,"How Many More Times"),
                Musica(39,"I Can't Quit You Baby"),
                Musica(40,"I'm Gonna Crawl"),
                Musica(41,"Immigrant Song"),
                Musica(42,"In My Time of Dying"),
                Musica(43,"In The Evening"),
                Musica(44,"In The Light"),
                Musica(45,"Jennings Farm Blues"),
                Musica(46,"Kashmir"),
                Musica(47,"Key to the Highway/Trouble inMind"),
                Musica(48,"LA Drone"),
                Musica(49,"La La"),
                Musica(50,"Living Loving Main (She'sJust a Woman)"),
                Musica(51,"Misty Mountain Hop"),
                Musica(52,"Moby Dick"),
                Musica(53,"Night Flight"),
                Musica(54,"No Quarter"),
                Musica(55,"Nobody's Fault but Mine"),
                Musica(56,"Out on the Tiles"),
                Musica(57,"Over the Hills and Far Away"),
                Musica(58,"Ozone Baby"),
                Musica(59,"Poor Tom"),
                Musica(60,"Ramble On"),
                Musica(61,"Rock and Roll"),
                Musica(62,"Royal Orleans"),
                Musica(63,"Sick Again"),
                Musica(64,"Since I've Been Loving You"),
                Musica(65,"Somethin' Else"),
                Musica(66,"South Bound Suarez"),
                Musica(67,"Stairway to Heaven"),
                Musica(68,"Tangerine"),
                Musica(69,"Tea for One"),
                Musica(70,"Ten Years Gone"),
                Musica(71,"Thank You"),
                Musica(72,"That's the Way"),
                Musica(73,"The Battle of Evermore"),
                Musica(74,"The Crunge"),
                Musica(75,"The Girl I Love She Got LongBlack Wavy Hair"),
                Musica(76,"The Lemon Song"),
                Musica(77,"The Ocean"),
                Musica(78,"The Rain Song"),
                Musica(79,"The Rover"),
                Musica(80,"The Song Remains the Same"),
                Musica(81,"The Wanton Song"),
                Musica(82,"Trampled Under Foot"),
                Musica(83,"Travelling Riverside Blues"),
                Musica(84,"Walter's Walk"),
                Musica(85,"We're Gonna Groove"),
                Musica(86,"Wearing and Tearing"),
                Musica(87,"What Is and What ShouldNever Be"),
                Musica(88,"When the Levee Breaks"),
                Musica(89,"White Summer/Black MountainSide"),
                Musica(90,"Whole Lotta Love"),
                Musica(91,"You Shook Me"),
                Musica(92,"Your Time Is Gonna Come")*/

            )
        }
    }
}